name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5.1.1
    
      with:
        python-version: '3.11'
      
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install --deploy --dev --system
    
    - name: Lint code with Flake8
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=99

    - name: Set environment variable
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
    
    - name: Run tests with coverage
      run: |
        pipenv run coverage run --source='.' manage.py test
        pipenv run coverage report
        pipenv run coverage xml
      continue-on-error: false
    
    - name: Check coverage
      run: |
        pipenv run coverage report --fail-under=80
      continue-on-error: false


  containerize:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: elchoup/oc_lettings_image:${{ github.sha }}
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}

   

   
